### ISSUE TITLE
libmqm_r.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mattiamarteddu** [agebhar1/mq_exporter#35]
Hi, I was trying to use your exporter but the very moment I try to run the image "**quay.io/agebhar1/mq_exporter:latest**" I encounter this error:

```$ docker run quay.io/agebhar1/mq_exporter:latest```
```/opt/mq_exporter/mq_exporter: error while loading shared libraries: libmqm_r.so: cannot open shared object file: No such file or directory```

Could you tell me how to solve it?
Thank you

**Comment by mattiamarteddu** [comment]
I just downloaded the IBM MQ redistributable clients but inside it I can't find that library

**Comment by agebhar1** [comment]
Assume you're using Linux, the (dynamic) link to the library is https://ibm.biz/IBM-MQC-Redist-LinuxX64targz. Create a directory e.g. `mqm` and extract the archive into this directory. Then you can mount the directory while start the container `-v $(pwd)/mqm:/opt/mqm` from the directory where `mqm` exists (`ls` lists `mqm`).
