### ISSUE TITLE
How to monitor multiple channels?

### ISSUE THREAD

**Issue by liudingmin** [agebhar1/mq_exporter#68]
Hi, 
The default config file seems to support monitoring only 1 channel with multiple queues, but in my circumstance I need to monitor multiple channels, each associated with 1 or more queues. May I use '---' in config.yml to divide multiple configs for different channels? Thanks!

**Comment by agebhar1** [comment]
Hi,
currently the exporter is able to connect to one channel only. To export the metrics from multiple channels you have to run several instances of the exporter, one for each channel.

**Comment by liudingmin** [comment]
Finally I made it after I shifted my channel config info to a svrconn type one. Your project helps me a lot!

**Comment by liudingmin** [comment]
Finally I made it after I shifted my channel config info to a svrconn type one. Your project helps me a lot!

**Comment by liudingmin** [comment]
I tried monitoring MQ cluster and successfully obtained parameters of sender queues from channel A, but failed to get parameters of receiver queues from channel sub-A (I already run another instance to monitor channel sub-A). I found parameter 'mq_queue_up' of all receiver queues is 0, while the log referred to code 2068 (0814) (RC2068): MQRC_SELECTOR_NOT_FOR_TYPE.

**Comment by agebhar1** [comment]
It's not possible with the used API call [MQINQ](https://www.ibm.com/docs/en/ibm-mq/9.4?topic=calls-mqinq-inquire-object-attributes) to get the depth of a remote queue as far as I know.

**Comment by agebhar1** [comment]
I refreshed my knowledge about remote queues for IBM MQ. If you have two queue manager QM1 and QM2, and two clients. Client A is a sender and put messages to queue **Q1** on **QM1** through channel A. Queue Q1 is a remote queue with the target queue located on QM2 as queue Q1. Client B is a receiver and get messages from queue **Q1** on **QM2**. Assume client A is allowed through channel A to put messages to queue Q1 on QM1 and client B is allowed through channel B to put messages to queue Q1 on QM2.

Internally another local queue **Q1_QM2** with usage as transmission queue is used in interaction with both transmission channels QM1.QM2 on QM1 (sender) and on QM2 (receiver) to forward the messages from QM1 to QM2.

![ibmmq-remote](https://github.com/user-attachments/assets/a9af0e43-3958-410a-9898-2ff6ac5f3ad6)

With [MQINQ](https://www.ibm.com/docs/en/ibm-mq/9.4?topic=calls-mqinq-inquire-object-attributes) it's possible to read depth of Q1 on QM2. It's not possible to get the depth of the remote queue Q1 on QM1.

As long as client A have access to Q1_QM2 the depth can be queried by `MQINQ`. Which is the number of messages not transferred from QM1 to QM2. To get the number of unprocessed messages, produced by client A, you need to query the depth of Q1 on QM2.

**Comment by liudingmin** [comment]
> I refreshed my knowledge about remote queues for IBM MQ. If you have two queue manager QM1 and QM2, and two clients. Client A is a sender and put messages to queue **Q1** on **QM1** through channel A. Queue Q1 is a remote queue with the target queue located on QM2 as queue Q1. Client B is a receiver and get messages from queue **Q1** on **QM2**. Assume client A is allowed through channel A to put messages to queue Q1 on QM1 and client B is allowed through channel B to put messages to queue Q1 on QM2.
> 
> Internally another local queue **Q1_QM2** with usage as transmission queue is used in interaction with both transmission channels QM1.QM2 on QM1 (sender) and on QM2 (receiver) to forward the messages from QM1 to QM2.
> 
> ![ibmmq-remote](https://private-user-images.githubusercontent.com/2443866/352814008-a9af0e43-3958-410a-9898-2ff6ac5f3ad6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDM1NzgsIm5iZiI6MTcyNDQwMzI3OCwicGF0aCI6Ii8yNDQzODY2LzM1MjgxNDAwOC1hOWFmMGU0My0zOTU4LTQxMGEtOTg5OC0yZmY2YWM1ZjNhZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDg1NDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU2ZWVlYTJiOTQ2YzQ5ZWJiZWMyNzgwYmUyODY3ZmQ2MDA2ZGU0MWRjNmNlZWZlYmI3NjIwNzg3NThmYTI4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JK18Lj7tOxUD4ap1Bavu2vhJxwspCENd1kSeaA0RmvI)
> 
> With [MQINQ](https://www.ibm.com/docs/en/ibm-mq/9.4?topic=calls-mqinq-inquire-object-attributes) it's possible to read depth of Q1 on QM2. It's not possible to get the depth of the remote queue Q1 on QM1.
> 
> As long as client A have access to Q1_QM2 the depth can be queried by `MQINQ`. Which is the number of messages not transferred from QM1 to QM2. To get the number of unprocessed messages, produced by client A, you need to query the depth of Q1 on QM2.

Yeah I'm facing a MQ cluster like this, with a similar sender-receiver construction but two senders form a sender cluster. That's even more complicated. For I don't have access to client A, my work is accomplished (at the best I can do)with the help of your project!

**Comment by agebhar1** [comment]
> [...], my work is accomplished (the best I can do) with the help of your project!

Great. Thanks for the nice words!
